App({
  global:{
    currentLanguage:'zh',
    zh:{
      home:{
        home: '主页',
        myPay: '微信支付',
        edit: '编辑资料',
        cardlevel1: '红卡会员',
        cardlevel2: '银卡会员',
        cardlevel3: '金卡会员',
        myPoint:'我的积分',
        myCard:'我的卡券',
        activity:'最新活动',
        member:'会员权益',
        store:'门店查询',
        points:'积分',
        contactUs:'联系客服',
        serviceTel:'服务热线：',
        serviceTime:'服务时间：',
        serviceTimeDetail:'周一至周日',
        close: '关闭',
        pickUp:'收起',
        codeDesc:'使用时，出示此码'
      },
      member:{
        title:'会员等级介绍',
        content_1:'1. 消费1元 = 1积分（零售商品等除外）；',
        content_2:'2. 20积分抵1元，积分需要整单兑换（当笔积分有效期为次年的同月月底）;',
        content_3:'3. 会员使用权益时需出示会员卡或电子会员卡',
        content_4:'4. 会员权益暂不可累积使用或者与门店其他活动叠加使用',
        content_5:'5. 会员积分以及权益使用范围仅限咖世家咖啡所属门店（万达影城店、火车站店、机场店以及杭州阿里巴巴店、SSP店、COMPASS店除外）',
        content_5_1:'·如享受门店其他活动折扣，例如银行卡折扣，则不可以使用会员优惠券或者会员积分兑换权益',
        content_5_2:'·门店会员活动、会员优惠券以及会员积分兑换不可同时享用',
        content_5_3:'·累计杯数按正价产品累计，非正价产品不计入杯数',
        content_6: '6. 升级后的12个月内，若累计积分未达到您所在等级的积分，您将自动降级至当前积分相应等级，您将享受降级后相应等级的权益；',
        gold_1_1_1:'一年内累计',
        gold_1_1_2:'1500积分',
        gold_1_1_3:'即刻成为',
        gold_1_1_4:'金卡会员',
        gold_1_2_1:'正价消费任意手工调制饮品独享',
        gold_1_2_2:'满8杯赠1杯',
        gold_2_1_1:'升级次日获得',
        gold_2_1_2:'饮品免费',
        gold_2_1_3:'礼券一张',
        gold_2_2_1:'生日月获得',
        gold_2_2_2:'饮品免费',
        gold_2_2_3:'礼券一张',
        gold_3_1_1:'丰富的',
        gold_3_1_2:'会员专享活动',
        gold_3_2_1:'专属的',
        gold_3_2_2:'提前预购礼遇',
        silver_1_1_1:'一年内累计',
        silver_1_1_2:'700积分',
        silver_1_1_3:'即刻成为',
        silver_1_1_4:'金卡会员',
        silver_1_2_1:'正价消费任意手工调制饮品独享',
        silver_1_2_2:'满12杯赠1杯',
        silver_2_1_1:'升级次日获得',
        silver_2_1_2:'买一赠一',
        silver_2_1_3:'礼券一张',
        silver_2_2_1:'生日月获得',
        silver_2_2_2:'买一赠一',
        silver_2_2_3:'礼券一张',
        silver_3_1_1:'丰富的',
        silver_3_1_2:'会员专享活动',  
        red_1_1_1:'完成注册,即刻成为',
        red_1_1_2:'红卡会员,',
        red_1_1_3:'开始累计积分',
        red_1_2_1:'生日月获得',
        red_1_2_2:'买一赠一',
        red_1_2_3:'礼券一张',
        red_2_1_1:'首次消费满30，',
        red_2_1_2:'赠30元礼券',  
        red_2_2_1:'丰富的',
        red_2_2_2:'会员专享活动'
      },
      points:{
        flag: '积分',
        title: '积分中心',
        vipName: '红卡会员',
        current: '当前积分',
        upgrade: '距离升级积分',
        expire: '本月底将过期',
        tab1: '积分兑换',
        tab2: '最新活动',
        placeholder: '输入您的转赠积分',
        btnTxt: '积分转赠好友',
        subTitle: '积分记录',
      },
      redeem: {
        title: '积分兑换',
        tips: '更多积分兑换礼品',
        txt: '敬请期待'
      },
      share: {
        title: '送给大家',
        txt: '感觉自己壕壕哒',
        btnTxt: '分享给大家',
        btnTxtBack: '返回我的积分',
        btnTxtApt: '确认领取积分',
        tips: '你已成功抢到此积分',
        tipsNone: '已被他人领取',
      },
      userInfo: {
        title: '个人信息修改',
        requireType: '必填项',
        selectType: '选填项',
        selectsType: '选填项,可多选',
        sex: ['男', '女'],
        company: '所在公司',
        position: '职位',
        subTitle: '产品偏好',
        tips: '告诉我们你的产品偏好，可获得20积分',
        items: ['美式', '拿铁', '卡布奇诺', '摩卡', '醇艺白', '意式浓缩', '可塔朵', '茶饮', '巧克力'],
        btnTxt: '确认修改',
      },
    },
    en: {
      home:{
        home: 'Home',
        myPay: 'My Wallet',
        edit: 'Profile Updates',
        cardlevel1: 'Red Member',
        cardlevel2: '银卡会员',
        cardlevel3: '金卡会员',
        myPoint:'My Points',
        myCard:'My Coupons',
        activity:'Promotions',
        member:'Member Rewards',
        store:'Store Location',
        points:'points',
        contactUs:'Contact us',
        serviceTel:'Service HotLine：',
        serviceTime:'Service Time：',
        serviceTimeDetail:'Mon-Sun ',
        close: 'Closed',
        pickUp:'pack up',
        codeDesc:'Please present QR code'
      },
      member:{
        title:'Member Level Introduction',
        content_1:'1. You will earn 1 point for each￥1.00 you spend at designated Costa stores using your registered membership card (retail products etc. excluded).',
        content_2:'2. Every 20 points is worth ￥1.00. Points can only be redeemed if members have enough points to cover the full value of the order (The points earned will be valid to the end of the same month of your purchase of the following year).',
        content_3:'3. Members need to show the unique membership QR Code when using member benefits.',
        content_4:'4. Member benefits cannot be used multiple times in one order or be combined with other discounts and promotions at the same time.',
        content_5:'5. Member points and member benefits can only be used in designated stores under Costa Coffee (the stores in Wanda cinemas, train stations, airports, Alibaba Hangzhou, SSP, and COMPASS are excluded).',
        content_5_1:'·In-store discounts or promotions cannot be combined with member benefits (for example credit card discounts cannot be combined with member benefits).',
        content_5_2:'·Coupon and rewards redemption cannot be used at the same time.',
        content_5_3:'·Only beverages at full price as collecting points are eligible towards the number of beverages purchased.',
        content_6: '6. Twelve months after your membership level is upgraded, if the points you earned are below the threshold of your current membership level, you will be automatically transferred to the level that corresponds to your current points.',
        gold_1_1_1:'Earn ',
        gold_1_1_2:'1,500 points ',
        gold_1_1_3:'to become our ',
        gold_1_1_4:'Gold Member',
        gold_1_2_1:'Buy 8 beverages at full price to ',
        gold_1_2_2:'get 1 for free',
        gold_2_1_1:'Receive ',
        gold_2_1_2:'a free beverage ',
        gold_2_1_3:'coupon one day after your membership level has increased.',
        gold_2_2_1:'Receive ',
        gold_2_2_2:'a free beverage ',
        gold_2_2_3:'coupon during your Birthday month.',
        gold_3_1_1:'Exclusive ',
        gold_3_1_2:'Member Rewards ',
        gold_3_2_1:'Get to know new products and rewards ',
        gold_3_2_2:' first',
        silver_1_1_1:'Earn',
        silver_1_1_2:'700 points ',
        silver_1_1_3:'to become our ',
        silver_1_1_4:'silver Member',
        silver_1_2_1:'Buy 12 beverages at full price to ',
        silver_1_2_2:'get 1 for free',
        silver_2_1_1:'Receive',
        silver_2_1_2:'a free beverage',
        silver_2_1_3:'coupon one day after your membership level has increased.',
        silver_2_2_1:'Receive',
        silver_2_2_2:'a free beverage',
        silver_2_2_3:'coupon during your Birthday month.',
        silver_3_1_1:'Exclusive ',
        silver_3_1_2:'Member Rewards ',  
        red_1_1_1:'Complete registration to become our ',
        red_1_1_2:'Red Member,,',
        red_1_1_3:'and start to earn your points',
        red_1_2_1:'Receive',
        red_1_2_2:'a free beverage',
        red_1_2_3:'coupon during your Birthday month.',
        red_2_1_1:'First purchase over ¥30, will ',
        red_2_1_2:'get one complimentary ¥30 coupon',  
        red_2_2_1:'Exclusive ',
        red_2_2_2:'Member Rewards'
      },
      redeem: {
        title: 'Redeem Points',
        tips: 'More Options for Rewards Redmeption',
        txt: 'Coming soon'
      },
      points: {
        flag: 'Points',
        title: 'Point Center',
        vipName: 'Red Member',
        current: 'Current Point',
        upgrade: 'Points required to upgrade',
        expire: 'Expiring at then end of this month',
        tab1: 'Redeem Points',
        tab2: 'Promotions',
        placeholder: 'Enter the points given',
        btnTxt: 'Share with',
        subTitle: 'Points History',
      },
      share: {
        title: '送给大家',
        txt: '感觉自己壕壕哒',
        btnTxt: 'Share with friends',
        btnTxtBack: 'back',
        btnTxtApt: 'Confirm',
      },
      userInfo: {
        title: '个人信息修改',
        requireType: '必填项',
        selectType: '选填项',
        selectsType: '选填项,可多选',
        sex: ['男', '女'],
        company: '所在公司',
        position: '职位',
        subTitle: '产品偏好',
        tips: '告诉我们你的产品偏好，可获得20积分',
        items: 
        ['美式', '拿铁', '卡布奇诺', '摩卡', '醇艺白', '意式浓缩', '可塔朵', '茶饮', '巧克力'],
        btnTxt: '确认修改',
      }
    }
  },
  onLaunch: function () {

  }
})