App({
  global:{
    currentLanguage:'zh',
    zh:{
      home:{
        home: '主页',
        myPay: '微信支付',
        edit: '编辑资料',
        cardlevel1: '红卡会员',
        cardlevel2: '银卡会员',
        cardlevel3: '金卡会员',
        myPoint:'我的积分',
        myCard:'我的卡券',
        activity:'最新活动',
        member:'会员权益',
        store:'门店查询',
        points:'积分',
        contactUs:'联系客服',
        serviceTel:'服务热线：',
        serviceTime:'服务时间：',
        serviceTimeDetail:'周一至周日',
        close: '关闭',
        pickUp:'收起',
        codeDesc:'使用时，出示此码'
      },
      points:{
        flag: '积分',
        title: '积分中心',
        vipName: '红卡会员',
        current: '当前积分',
        upgrade: '距离升级积分',
        expire: '本月底将过期',
        tab1: '积分兑换',
        tab2: '最新活动',
        placeholder: '输入您的转赠积分',
        btnTxt: '积分转赠好友',
        subTitle: '积分记录',
      },
      redeem: {
        title: '积分兑换',
        tips: '更多积分兑换礼品',
        txt: '敬请期待'
      },
      share: {
        title: '送给大家',
        txt: '感觉自己壕壕哒',
        btnTxt: '分享给大家',
        btnTxtBack: '返回我的积分',
        btnTxtApt: '确认领取积分',
        tips: '你已成功抢到此积分',
        tipsNone: '已被他人领取',
      },
      userInfo: {
        title: '个人信息修改',
        requireType: '必填项',
        selectType: '选填项',
        selectsType: '选填项,可多选',
        sex: ['男', '女'],
        company: '所在公司',
        position: '职位',
        subTitle: '产品偏好',
        tips: '告诉我们你的产品偏好，可获得20积分',
        items: ['美式', '拿铁', '卡布奇诺', '摩卡', '醇艺白', '意式浓缩', '可塔朵', '茶饮', '巧克力'],
        btnTxt: '确认修改',
      },
    },
    en: {
      home:{
        home: 'Home',
        myPay: 'My Wallet',
        edit: 'Profile Updates',
        cardlevel1: 'Red Member',
        cardlevel2: '银卡会员',
        cardlevel3: '金卡会员',
        myPoint:'My Points',
        myCard:'My Coupons',
        activity:'Promotions',
        member:'Member Rewards',
        store:'Store Location',
        points:'points',
        contactUs:'Contact us',
        serviceTel:'Service HotLine：',
        serviceTime:'Service Time：',
        serviceTimeDetail:'Mon-Sun ',
        close: 'Closed',
        pickUp:'pack up',
        codeDesc:'Please present QR code'
      },
      redeem: {
        title: 'Redeem Points',
        tips: 'More Options for Rewards Redmeption',
        txt: 'Coming soon'
      },
      points: {
        flag: 'Points',
        title: 'Point Center',
        vipName: 'Red Member',
        current: 'Current Point',
        upgrade: 'Points required to upgrade',
        expire: 'Expiring at then end of this month',
        tab1: 'Redeem Points',
        tab2: 'Promotions',
        placeholder: 'Enter the points given',
        btnTxt: 'Share with',
        subTitle: 'Points History',
      },
      share: {
        title: '送给大家',
        txt: '感觉自己壕壕哒',
        btnTxt: 'Share with friends',
        btnTxtBack: 'back',
        btnTxtApt: 'Confirm',
      },
      userInfo: {
        title: '个人信息修改',
        requireType: '必填项',
        selectType: '选填项',
        selectsType: '选填项,可多选',
        sex: ['男', '女'],
        company: '所在公司',
        position: '职位',
        subTitle: '产品偏好',
        tips: '告诉我们你的产品偏好，可获得20积分',
        items: 
        ['美式', '拿铁', '卡布奇诺', '摩卡', '醇艺白', '意式浓缩', '可塔朵', '茶饮', '巧克力'],
        btnTxt: '确认修改',
      }
    }
  },
  onLaunch: function () {

  }
})